### ISSUE TITLE
[Pattern] Performance Test

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-patterns/service-mesh-patterns#11]
#### Current Behavior
Users need a base pattern to describe a performance test and from which to customize their performance tests.

#### Desired Behavior
A common descriptor of what a Service Mesh performance-based performance test pattern is needed.

#### Implementation
SMP-compatible pattern

#### Acceptance Tests
1. Meets SMP spec.
2. Importable into Meshery.

#### Mockups
```
performance_test:
  duration: 200s
  rps: 10
  threads: 10
  success_conditions:
    - request_count["name=checkout"]:
        value: 2000
        tolerance: 0.01%
    - request_count["name=payments_v1, status=200"]:
        value: 1992
        tolerance: 0.01%
    - request_count["name=payments_v1, status!=200"]:
        value: 0
        tolerance: 0.01%
    - request_count["name=payments_v2, status=200"]:
        value: 0
    - request_count["name=payments_v2 status!=200"]:
        value: 8
        tolerance: 0.01%
```

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
